apiVersion: v1
kind: Service
metadata:
  name: nginx-deployment
  namespace: nginx-laba
  labels:
      app: nginx-app
spec:
  selector:
      app: nginx-app
  type: NodePort
  ports:
    - nodePort: 31101
      protocol: TCP
      port: 80
      targetPort: 80
  