apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: nginx-laba
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-app
  template:
    metadata:
      labels:
        app: nginx-app
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /etc/nginx/conf.d/default.conf
          name: nginxconfvol
          subPath: default.conf
      volumes:
      - name: nginxconfvol
        configMap:
          name: nginx-configmap

---
apiVersion: v1
kind: Service
metadata: 
    name: nginx-deployment
    namespace: nginx-laba
    labels:
        app: nginx-app
spec:
    selector:
        app: nginx-app
    type: NodePort
    ports:
    - port: 8888
      nodePort: 31101