apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: nginx-laba
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-app
  template:
    metadata:
      labels:
        app: nginx-app
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /etc/nginx/conf.d/default.conf
          name: nginxconfvol
          subPath: default.conf
        - mountPath: /usr/share/nginx/html
          name: nginxhtml
      initContainers:
      - name: init-index
        image: busybox:latest
        volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: nginxhtml
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        command: ['sh', '-c', 'echo "Pod name - ${POD_NAME}" >> /usr/share/nginx/html/index.html']
      volumes:
      - name: nginxconfvol
        configMap:
          name: nginx-configmap
      - name: nginxhtml
        persistentVolumeClaim:
          claimName: task10-pv-claim
