- hosts: master
  become: false
  tasks:
    
  - name: Copy yaml file
    copy:
      src: nginx-init.yml
      dest: ./

  - name: Set POD_NAME variable to index.html
    shell: kubectl apply -f nginx-init.yml    
    
