apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: task10-pv-claim
  namespace: nginx-laba
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: nginx-laba
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-app
  template:
    metadata:
      labels:
        app: nginx-app
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /etc/nginx/conf.d/default.conf
          name: nginxconfvol
          subPath: default.conf
        - mountPath: /usr/share/nginx/html
          name: nginxhtml
      volumes:
      - name: nginxconfvol
        configMap:
          name: nginx-configmap
      - name: nginxhtml
        persistentVolumeClaim:
          claimName: task10-pv-claim